version: "3.7"

services:
  nomad:
    image: mr-karan/nomad:1.3.0
    container_name: nomad
    restart: always
    build:
      context: ./
      dockerfile: ./nomad.Dockerfile
      args:
        NOMAD_VERSION: 1.3.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./configs/nomad.hcl:/etc/nomad.d/nomad.hcl:ro
      - /opt/nomad/data:/opt/nomad/data
    privileged: true
    network_mode: host
    depends_on:
      - consul

  consul:
    image: consul:1.12
    container_name: consul
    restart: always
    volumes:
      - /opt/consul/data:/opt/consul/data
      - ./configs/consul.hcl:/etc/consul.d/consul.hcl:ro
    network_mode: host
    command: "agent -config-dir=/etc/consul.d/"
